spring.application.name=food_delivery

#mongodb configuartion
#spring.data.mongodb.uri=mongodb://localhost:27017/foodies
spring.data.mongodb.uri=mongodb://localhost:27017/foodies
spring.data.mongodb.database=foodies


#aws s3 configuration
#aws.access.key=${AWS_ACCESS_KEY}
#aws.secret.key=${AWS_SECRET_KEY}
aws.access.key=awsaccesskey
aws.secret.key=awsaccesskey
aws.region=us-east-1
aws.s3.bucketname=food-app-feb8

#jwt-token
jwt.secret.key=n8F4zqLp9Vx2rW7jTmK6bYcU1dR56YVioWeW7jTmK6bYcU1dR56YVioWe

#razorpay configuration
#razorpay_key=${RAZORPAY_KEY}
#razorpay_secret=${RAZORPAY_SECRET}
razorpay_key=vamsi
razorpay_secret=vamsi_secret